### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arikoza** [e1z0/AnotherRTSP#2]
Good afternoon. Tell me, I installed the program on a second computer and it doesn’t start, it gives an error:
Имя журнала:   Application
Источник:      Application Error
Дата:          24.05.2024 7:44:57
Код события:   1000
Категория задачи:События сбоев приложения
Уровень:       Ошибка
Ключевые слова:
Пользователь:  Mira\arikoza
Компьютер:     Mira
Описание:
Имя сбойного приложения: AnotherRTSP.exe, версия: 1.0.0.0, метка времени: 0x65ed9afb
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.22621.3527, метка времени: 0xf436709b
Код исключения: 0xe0434352
Смещение ошибки: 0x001498b2
Идентификатор сбойного процесса: 0x0x3558
Время запуска сбойного приложения: 0x0x1DAAD95204B6E57
Путь сбойного приложения: C:\Users\arikoza\AppData\Roaming\AnotherRTSP\AnotherRTSP.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 1bc8ae35-5745-4418-8f94-c9f1b2c5b367
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-05-24T04:44:57.1992890Z" />
    <EventRecordID>4128</EventRecordID>
    <Correlation />
    <Execution ProcessID="15344" ThreadID="11296" />
    <Channel>Application</Channel>
    <Computer>Mira</Computer>
    <Security UserID="S-1-5-21-2785729414-4208444686-1834555080-1006" />
  </System>
  <EventData>
    <Data Name="AppName">AnotherRTSP.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">65ed9afb</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.3527</Data>
    <Data Name="ModuleTimeStamp">f436709b</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">001498b2</Data>
    <Data Name="ProcessId">0x3558</Data>
    <Data Name="ProcessCreationTime">0x1daad95204b6e57</Data>
    <Data Name="AppPath">C:\Users\arikoza\AppData\Roaming\AnotherRTSP\AnotherRTSP.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">1bc8ae35-5745-4418-8f94-c9f1b2c5b367</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>

and second

Имя журнала:   Application
Источник:      .NET Runtime
Дата:          24.05.2024 7:44:56
Код события:   1026
Категория задачи:Отсутствует
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     Mira
Описание:
Приложение: AnotherRTSP.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.DllNotFoundException
   в EasyPlayerNetSDK.PlayerSdk.EasyPlayer_Init(System.String)
   в AnotherRTSP.CustomUI.Init()
   в AnotherRTSP.Program.Main()

Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-05-24T04:44:56.9366634Z" />
    <EventRecordID>4127</EventRecordID>
    <Correlation />
    <Execution ProcessID="13656" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Mira</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Приложение: AnotherRTSP.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.DllNotFoundException
   в EasyPlayerNetSDK.PlayerSdk.EasyPlayer_Init(System.String)
   в AnotherRTSP.CustomUI.Init()
   в AnotherRTSP.Program.Main()

</Data>
  </EventData>
</Event>

How to solve this problem?

**Comment by e1z0** [comment]
It looks like that some dll's can't be found EasyPlayerNetSDK.PlayerSdk.EasyPlayer_Init means it can't find EasyPlayer-RTSP.NetSDK.dll please check your installation folder. Also open AnotherRTSP.ini and check if "CustomLayout=1" is specified in [General] section.

**Comment by arikoza** [comment]
![image](https://github.com/e1z0/AnotherRTSP/assets/93445603/77ed12d9-9212-4ab0-aacc-92e612471441)
![image](https://github.com/e1z0/AnotherRTSP/assets/93445603/ec519e72-54ca-4897-b6ea-cbfbd3024abd)

**Comment by e1z0** [comment]
Whats in AnotherRTSP.log?

**Comment by arikoza** [comment]
2024-05-22 09:11:19 -> Program started. Logging enabled!
2024-05-22 09:14:22 -> Program started. Logging enabled!
2024-05-22 12:37:53 -> Program started. Logging enabled!
2024-05-22 13:46:05 -> Program started. Logging enabled!
2024-05-22 18:38:29 -> Program started. Logging enabled!
2024-05-23 10:00:29 -> Program started. Logging enabled!
2024-05-23 14:00:09 -> Program started. Logging enabled!
2024-05-23 21:38:48 -> Program started. Logging enabled!
2024-05-24 07:44:56 -> Program started. Logging enabled!

**Comment by arikoza** [comment]
I didn’t find the problem, but I solved it, installed all the requirements for WinXP and everything worked

**Comment by maxdal89** [comment]
i have the same problem. On windows 11 i installed:

- Microsoft Visual C++ 2008 Redistributable package
- Microsoft Visual C++ 2010 Redistributable package
- .NET Framework 4.0 client package mirror

on Windows 11 i have not found One Core API compatible.

when i try to launch the app does not happen anyting. 

log file contains:

Timestamp->Program started. Logging enabled!

what i do to solve it? there are some requirment to satisfy?

**Comment by arikoza** [comment]
Microsoft Visual C++ 2005 install, restart PC

**Comment by maxdal89** [comment]
I tried but the app doesn't start
