### ISSUE TITLE
!!VIRUS!! Do not download

### ISSUE THREAD

**Issue by lotsokluze** [e1z0/AnotherRTSP#7]
Doesn't even run. Luckily Tinywall is installed and was able to block the botnet attempt.

**Comment by e1z0** [comment]
You either have VC++ 2010 runtime or .NET Framework 4.0 missing on your system. There are so many antivirus vendors and some of them are more threats than provides any protection at all. You must be running one of it, antivirus that marks all unknown software as malicious. Project have all source code provided, please investigate, compile yourself if you do not trust precompiled binaries, it's your choice. There are no any malicious code in this software, lol.. 

Again, provide specific examples of where and how the malicious activity occurs with evidence, not empty words. If your competence does not allow you to do this, then please do not shout loudly. Of course, no one is protected from laziness, if you are lazy to read and study, it is your personal problem. So please don't spread lies or promote mistrust.
Open source is based on mutual trust and respect for both the user and the code developer.
